### ISSUE TITLE
Vignettes have a lot mistakes

### ISSUE THREAD

**Issue by NiklausZZZ** [jishnu-lab/SLIDE#33]
Vignettes have a lot mistakes, such as:
![image](https://github.com/jishnu-lab/SLIDE/assets/156153907/7e70e1f6-4ef3-44fd-abc0-dceb86f4eb74)

And,
![image](https://github.com/jishnu-lab/SLIDE/assets/156153907/27579a13-95e6-4fa1-8d90-5274c5106889)

The vignettes may be not well understood for users.

**Comment by TranscriptionFactory** [comment]
The first is an easy fix (thanks for catching the typo!), but please clarify the issue with the second. Thanks for pointing these out @NiklausZZZ !

**Comment by NiklausZZZ** [comment]
![image](https://github.com/jishnu-lab/SLIDE/assets/156153907/c9336181-d20a-4a0b-bfb9-37f0a8d75a81)

**Comment by NiklausZZZ** [comment]
> The first is an easy fix (thanks for catching the typo!), but please clarify the issue with the second (the yaml file path is used to load the yaml parameters, which are then checked for correct inputs). Thanks for pointing these out @NiklausZZZ !

Thank you for your quick reply! Indeed, `yaml_path` is the directory of yaml file:
```R
checkDataParams(yaml_path)
Error in input_params$x_path : $ operator is invalid for atomic vectors
````
Used `checkDataParams(input_params)` will work:
![image](https://github.com/jishnu-lab/SLIDE/assets/156153907/24f4344d-c57d-4f5b-ad9d-f8752cd9130e)

**Comment by NiklausZZZ** [comment]
> ![image](https://private-user-images.githubusercontent.com/156153907/335801693-c9336181-d20a-4a0b-bfb9-37f0a8d75a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDYwMzYsIm5iZiI6MTcxNzI0NTczNiwicGF0aCI6Ii8xNTYxNTM5MDcvMzM1ODAxNjkzLWM5MzM2MTgxLWQyMGEtNGEwYi1iZmI5LTM3ZjBhOGQ3NWE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjQyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDk2YjQ2NWM2ZTlkM2U5ODA3MDA3YzkwOGFjZjU3NjI2NzllZDM3N2E4NmQzNmM3NDM4ZTY1YzBiNmY4NTg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j6xM_K1PD0qw4KKktOHw-JQuRMcSPUo4uGF1gWZz6io)

Does the description here match the picture? I am a lot confused. Any explanation would be greatly appreciated!

**Comment by TranscriptionFactory** [comment]
> Does the description here match the picture? I am a lot confused. Any explanation would be greatly appreciated! ![image](https://private-user-images.githubusercontent.com/156153907/335801693-c9336181-d20a-4a0b-bfb9-37f0a8d75a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNDY0ODcsIm5iZiI6MTcxNzI0NjE4NywicGF0aCI6Ii8xNTYxNTM5MDcvMzM1ODAxNjkzLWM5MzM2MTgxLWQyMGEtNGEwYi1iZmI5LTM3ZjBhOGQ3NWE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMjQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2UwMTA0YzUxZTljYjI1ODgxNWExNWNlMTIyNDcxZjQzZDk5M2EyZjNmYzAzYjM5MWMwMDE3ZTQ2MzYyYzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YTW6Y-ou9M7mcr550IvxMpYi45U_h_fL0XlfHbionPw)

explanation has been generalized and updated

**Comment by NiklausZZZ** [comment]
Thanks!

**Comment by TranscriptionFactory** [comment]
Thanks @NiklausZZZ - Please let us know if you find anything else!

**Comment by NiklausZZZ** [comment]
By the way, does SLIDE require the expression matrix (which is easy to understand) to be combined with phenotypic information (e.g., treatment response, age, gender, mutation)? It seems that phenotypic information is necessary.

**Comment by TranscriptionFactory** [comment]
Yes, SLIDE requires a single response label for regression/classification. Agreed re: additional phenotypic info necessary - currently, we do not integrate multiple responses but that is a great idea for next steps!
